# Use an official Python runtime as a parent image
FROM python:3.12.2

# Set the working directory inside the container
WORKDIR /textgames

# Copy the app's code into the container
COPY ./src/ ./

# # Copy the requirements file into the container
COPY requirements.txt ./

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the app runs on
EXPOSE 8501

# Command to run the app
CMD ["streamlit", "run", "app.py", "--server.fileWatcherType", "none"]