services:
  curation:
    container_name: textgames-dev
    build:
      context: .
      dockerfile: Dockerfile-textgames
    ports:
      - "8501:8501"
    volumes:
      - ./textgames:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
  
  